version: '3.9'

services:
  api:
    build: ./api
    container_name: ellp_api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  web:
    build: ./web
    container_name: ellp_web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: ellp_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ellp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: